disabled = false
locale = "ru"
label = "Русский"
weight = 2
title = "Нажмите любую клавишу"
contentDir = "content/ru"

[params]
  displayName = "RU"
  isoCode = "ru"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
  name = "Иван Филинков"
  image = "img/avatar.jpg"
  headline = "Технический писатель"
  links = [
    { github = "https://github.com/Avonae" },
    { linkedin = "https://www.linkedin.com/in/filinkov-ivan" },
    { telegram = "https://t.me/Press_Any" },
  ]
